### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by bananabot1024** [bananabot1024/USACO-AStar-Gold#1]
## Week 1: Searching Review 1
- [x] Laser Phone (lphone)
- [x] Catch that Cow (catchcow)
- [ ] Scales (scales)
- [ ] Tractor (tractor)
- [ ] What's Up with Gravity? (gravity)
- [ ] The Climbing Wall (wall)
